export const roles = Object.freeze({
	ADMIN: 'ADMIN',
	DEFAULT_USER: 'DEFAULT_USER',
});

export const health_statuses = Object.freeze({
	HEALTHY: 'HEALTHY',
	COMPROMISED: 'COMPROMISED',
});

export const allPermissions = Object.freeze({
	READ_USERS: 'READ_USERS',
	MODIFY_USERS: 'MODIFY_USERS',
	READ_LOCATIONS: 'READ_LOCATIONS',
	MODIFY_LOCATIONS: 'MODIFY_LOCATIONS',
	READ_APPEARANCES: 'READ_APPEARANCES',
	MODIFY_APPEARANCES: 'MODIFY_APPEARANCES',
});
